apiVersion: apps/v1
kind: Deployment 
metadata: 
  name: my-dep
spec: 
  replicas: 2
  selector: 
    matchLabels:
      app: my-dep-app

  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: my-dep-app
    spec:
      containers:
      - name: my-dep-cont
        image: nginx
        ports:
        - containerPort: 80

---
apiVersion: apps/v1
kind: ReplicaSet
metadata: 
  name: my-rs
spec: 
  replicas: 2
  selector: 
    matchLabels:
      app: my-rs-app

 
  template:
    metadata:
      labels:
        app: my-rs-app
    spec:
      containers:
      - name: my-rs-cont
        image: httpd
        ports:
        - containerPort: 80        
---
apiVersion: apps/v1
kind: DaemonSet 
metadata: 
  name: my-deamon
spec: 
 
  selector: 
    matchLabels:
      app: my-d-app

  template:
    metadata:
      labels:
        app: my-d-app
    spec:
      nodeSelector:
        kubernetes.io/hostname: controlplane        
      containers:
      - name: my-dep-cont
        image: httpd
        ports:
        - containerPort: 80